FROM registry.cells.es/docker/payara/server-full:6.2025.3-jdk21

USER root

RUN apt-get update
RUN apt-get install curl python3 -y

USER payara

RUN mkdir ./testbox_scripts/
COPY ./scripts/ ./testbox_scripts/

ENTRYPOINT ["sh", "-c", "./scripts/payara6_entrypoint.sh"]